title = "Local Gitleaks Config"

[extend]

[allowlist]
description = "False positives permitidos"
paths = [
  '''tests/.*''',
  '''\.secret-allowlist'''
]
regexes = [
  '''EXEMPLO_TOKEN_FAKE_123'''
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|secret|token)['"\s:=]{0,10}[A-Za-z0-9_\-]{16,64}'''
tags = ["apikey", "generic"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9A-Za-z]{36}'''
tags = ["github", "token"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key (heurística)"
regex = '''(?i)aws(.{0,20})?(secret|key)['"\s:=]{0,10}([A-Za-z0-9/+=]{40})'''
tags = ["aws", "key"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-[A-Za-z0-9-]{10,48}'''
tags = ["slack", "token"]

[[rules]]
id = "private-key"
description = "Private Key Block"
regex = '''-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "jwt"
description = "Provável JWT"
regex = '''eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}'''
tags = ["jwt", "token"]

