name: Security / Secrets Scan

on:
  pull_request:

jobs:
  gitleaks:
    name: Security Leaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout (full history para varredura correta)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --config .gitleaks.toml --redact --verbose
